site_name: Documentation

site_dir: ../../site/en
site_url: https://example.com/en/
repo_url: https://github.com/yaegashi/azdops-nginx-site
edit_uri: blob/main/docs/en/docs

theme:
  name: material
  language: en
  features:
    - navigation.top
    - content.action.edit
    - content.code.copy

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja

plugins:
  - search:
      lang: en
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
