site_name: Documentation

site_dir: ../../site/ja
site_url: https://example.com/ja/
repo_url: https://github.com/yaegashi/azdops-nginx-site
edit_uri: blob/main/docs/ja/docs

theme:
  name: material
  language: ja

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja

plugins:
  - search:
      lang: ja

nav:
  - index.md
